# .readthedocs.yaml - Read the Docs configuration file.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details.

version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
    jobs:
        post_checkout:
            - git fetch --unshallow
        pre_install:
            - pip install -r requirements.d/rtd.txt
            - python setup.py build_cython
            - python setup.py build_ext --inplace
    apt_packages:
        - build-essential
        - pkg-config
        - libfuse3-dev

python:
    install:
        - method: pip
          path: .

sphinx:
    configuration: rst/conf.py
